name: Publish Package

on:
    release:
        types: [created]
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  registry-url: "https://registry.npmjs.org"

            - name: Setup Yarn
              run: |
                  rm -rf .yarn .yarnrc.yml
                  corepack enable
                  corepack prepare yarn@3.6.1 --activate
                  echo 'nodeLinker: node-modules' > .yarnrc.yml
                  echo 'enableGlobalCache: true' >> .yarnrc.yml
                  echo 'enableImmutableInstalls: false' >> .yarnrc.yml

            - name: Install dependencies
              run: |
                  yarn install
                  yarn add -D @babel/core@^7.20.0 @babel/preset-env@^7.20.0

            - name: Type check
              run: yarn typecheck

            - name: Lint
              run: yarn lint

            - name: Build
              run: yarn prepare

            - name: Publish to NPM
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
